In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.DataFrame([[8,8,1],[7,9,1],[6,10,0],[5,5,0]], columns=['cgpa', 'profile_score', 'placed'])

In [3]:
df.head()

,cgpa,profile_score,placed
0,8,8,1
1,7,9,1
2,6,10,0
3,5,5,0


In [4]:
import tensorflow
from tensorflow import keras
from keras import Sequential
from keras.layers import Dense

In [5]:
model = Sequential()

model.add(Dense(2, activation='sigmoid', input_dim=2))
model.add(Dense(1, activation='sigmoid'))

C:\Users\opera\anaconda3\envs\Deep_Learning\Lib\site-packages\keras\src\layers\core\dense.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [6]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 2)              │             6 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 1)              │             3 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 9 (36.00 B)

 Trainable params: 9 (36.00 B)

 Non-trainable params: 0 (0.00 B)

In [7]:
model.get_weights()

[array([[0.00244927, 0.31015635],
        [1.1104177 , 0.02062762]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[-0.9790153 ],
        [ 0.31665397]], dtype=float32),
 array([0.], dtype=float32)]

In [8]:
new_weights = [
    np.array([[0.1, 0.1], [0.1, 0.1]], dtype=np.float32),
    np.array([0., 0.], dtype=np.float32),
    np.array([[0.1], [0.1]], dtype=np.float32),
    np.array([0.], dtype=np.float32)
]

In [9]:
model.set_weights(new_weights)

In [10]:
model.get_weights()

[array([[0.1, 0.1],
        [0.1, 0.1]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[0.1],
        [0.1]], dtype=float32),
 array([0.], dtype=float32)]

In [11]:
optimizer = keras.optimizers.Adam(learning_rate=0.001)
model.compile(loss='binary_crossentropy',optimizer=optimizer)

In [12]:
model.fit(df.iloc[:,0:-1].values,df['placed'].values,epochs=1150,verbose=1,batch_size=1)

Epoch 1/1150
4/4 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 0.6952  
Epoch 2/1150
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.6944 
Epoch 3/1150
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.6943 
Epoch 4/1150
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.6941 
Epoch 5/1150
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.6941 
Epoch 6/1150
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.6941 
Epoch 7/1150
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.6943 
Epoch 8/1150
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.6940 
Epoch 9/1150
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.6941 
Epoch 10/1150
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.6940 
Epoch 11/1150
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.6938 
Epoch 12/1150
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.6938 
Epoch 13/1150
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.6938 
Epoch 14/1150
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.6940 
Epoch 15/1150
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.6939 
Epo

In [13]:
model.get_weights()

[array([[ 0.31927925,  0.31927925],
        [-0.12050799, -0.12050799]], dtype=float32),
 array([-0.58681595, -0.58681595], dtype=float32),
 array([[0.19015773],
        [0.19015773]], dtype=float32),
 array([-0.16236988], dtype=float32)]